version: "3"
services:
  mimir:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: interstellar
      POSTGRES_PASSWORD: gnosis
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
        test: pg_isready -d interstellar -U postgres
        interval: 10s
        timeout: 120s
        start_period: 15s
  apollo:
    build: node/
    ports:
      - "4000:4000"
    volumes:
      - ./node:/app
      - /app/node_modules
    environment:
      - PORT=4000
    depends_on:
      mimir:
        condition: service_healthy

volumes:
  data:
