version: "3"
services:
  apollo:
    build: node/
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
      - /app/node_modules
    environment:
      - PORT=3000
  mimir:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: knowledge
