version: "3"
services:
  mimir:
    image: postgres:alpine
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
        test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
        interval: 5s
        timeout: 120s
        start_period: 15s
  apollo:
    build:
      context: node/
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - "${APOLLO_PORT}:${APOLLO_PORT}"
    volumes:
      - ./node:/app
      - /app/node_modules
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APOLLO_PORT: ${APOLLO_PORT}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      mimir:
        condition: service_healthy

volumes:
  data:
